openapi: 3.0.1
info:
  title: templatevalue
  description: templatevalue
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1

paths:
  /example:
    post:
      summary: Example API for testing Axios and DB connection
      responses:
        200:
          description: Success
        403:
          description: Fail

  /file:
    post:
      summary: Example API for testing file upload
      requestBody:
        description: Example body
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        201:
          description: Success
        403:
          description: Fail

components:
  schemas:
    ExampleBody:
      title: exampleBody
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
