openapi: 3.0.1
info:
  title: templatevalue
  description: templatevalue
  version: 1.0.0
servers:
  - url: https://localhost:3000/api/v1

paths:
  /example:
    post:
      summary: Create a new example
      # requestBody:
      #   description: Example body
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/ExampleBody'
      #   required: true
      responses:
        200:
          description: Success
        403:
          description: Fail

components:
  schemas:
    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
